### ISSUE TITLE
fty_metric_tpower_server.cc:291 : Assertion `timestamp == timestamp_new' failed

### ISSUE THREAD

**Issue by jimklimov** [42ity/fty-metric-tpower#26]
Sporadic failure in Travis during build of #25, went away after restarting the job.

Above the huge and scary `valgrind` leak report, it said the test failed upon assertion (hence the leak of ungraceful exit):

````
lt-fty_metric_tpower_selftest: src/fty_metric_tpower_server.cc:291: \
  void fty_metric_tpower_server_test(bool): Assertion `timestamp == timestamp_new' failed.
````

Guessing without a look at code, this maybe because of timing issues under the slower valgrind where more generous polling timeouts etc. proved to solve sporadic faults in other zeromq-ecosystem tests.

**Comment by FrancoisRegisDegott-eaton** [comment]
out of date
